apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: plan-self
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/danielcandido/plan-self-api:latest
          ports:
            - containerPort: 3001
